/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 vinylrecord.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/vinylrecord.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <group rotation={[-0.357, 0.1, 0.984]}>
          <mesh geometry={nodes.VinylRecord3_VinylRecord3_0.geometry} material={materials.VinylRecord3} rotation={[0.105, -0.355, -0.01]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vinylrecord.glb')
